version: '3.8'

services:
  app:
    image: openjdk:17-jdk-slim
    container_name: restaurant
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Mapeamento da porta
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/RestaurantAPI
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1590
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs

  db:
    image: postgres:14
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: RestaurantAPI
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1590
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
